openapi: 3.0.0
info:
  title: Platform API
  description: This is a schema definition for the example gateway API
  version: 1.0.1

paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200':    # status code
          description: A JSON array of user
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                required:
                  - items

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        kind:
          type: string
        email:
          type: string
      required:
        - id
        - kind
        - email